config/routes.rb
Rails.application.routes.draw do

  # ユーザ用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲスト用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # アドミン用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do

    root to: 'homes#top'
    get 'search' => 'searches#search'
    get '/mypage' => 'users#mypage'
    get 'users/confirm_deleted' => 'users#confirm_deleted', as: 'confirm_deleted'
    patch 'users/is_deleted' => 'users#is_deleted', as: 'is_deleted'
    resources :users, only: [:index, :show, :edit, :update] do
     resource :relationships, only: [:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :posts do
      get :favorites, on: :collection
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create]
    end
    resources :comments, only: [:destroy]
  end

  namespace :admin do

    root to: 'posts#index'
    get 'search' => 'searches#search'
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:show, :destroy]
    resources :comments, only: [:destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true, length: {maximum:100}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  validates :goal, presence: true, length: { maximum: 30 }
  validates :action, presence: true, length: { maximum: 100 }

  has_one_attached :image

  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  has_many :comments, dependent: :destroy

  #引数で渡されたユーザidがFavoritesテーブル内に存在するか確認する
  def favorited_by?(user)
    #後置修飾の"if user"は記述しないと非ログイン時にいいね機能のある画面を表示できないため記述
    favorites.exists?(user_id: user.id) if user
  end

  #目標を曖昧検索するためのメソッド
  def self.search_for(content)
    if content != nil
      where('goal LIKE ?', '%' + content + '%').order(created_at: :desc)
    else
      order(created_at: :desc)
    end
  end

  def self.sort_index(sort)
    case (sort)
      #投稿のいいねが多い順に並び替え
      when 'favorite_count'
        eager_load(:favorites).group('posts.id').order('count(favorites.post_id) DESC')
      #投稿のコメントが多い順に並び替え
      when 'comment_count'
        eager_load(:comments).group('posts.id').order('count(comments.post_id) DESC')
      else
        #投稿の新しい順に並び替え
        order(created_at: :desc)
    end
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  validates :status, presence: true

  has_one_attached :profile_image

  # ユーザーに在籍状況ステータス”公開”、”非公開”、”退会のユーザー”
  enum status: { released: 0, nonreleased: 1, withdraw: 2 }

  #ユーザーステータスが”退会”以外のユーザーをユーザー一覧で表示させるためのscope
  scope :active_user, -> { where(status: 0).or(where(status: 1)).order(created_at: :desc) }

  has_many :posts, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :comments, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant({gravity: :center, resize: "#{width}x#{height}^", crop: "#{width}x#{height}+0+0"}).processed
  end

  def active_for_authentication?
    super && !self.withdraw?
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def follow(user)
    relationships.find_or_create_by(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content)
    if content != nil
      where('name LIKE ?', '%' + content + '%').order(created_at: :desc)
    else
      order(created_at: :desc)
    end
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  
  before_action :authenticate_admin!

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @posts = Post.sort_index(params[:sort]).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to admin_root_path
  end

end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController

  before_action :authenticate_admin!

#キーワード検索
  def search
    @content = params[:content]
    @users = User.search_for(@content).page(params[:page])
    @posts = Post.search_for(@content).page(params[:page])
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  before_action :user_exists?, only: [:new]
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    admin_root_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def user_exists?
    if user_signed_in?
      redirect_to root_path
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @users = User.all.order(created_at: :desc).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(6)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
      flash[:notice] = "編集に成功しました。"
    else
      render :edit
    end
  end

#不適切な投稿をされる方の退会処理
  def is_deleted
    @user = current_user
    @user.update(status: 2)
    reset_session
    flash[:notice] = "退会処理を実行いたしました。"
    redirect_to admin_users_path
  end

private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_classname

  def set_classname
    if params[:controller] == 'public/homes' && params[:action] == 'top'
      @classname = 'top-body'
    else
      @classname = 'top-except'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/comments/_count.html.erb
コメント数：<%= post.comments.count %>

app/views/admin/comments/_index.html.erb
<div class="card-text">
  <% post.comments.each do |comment| %>
    <div class="media border rounded mb-3">
      <div class="p-3">
        <%= link_to user_path(comment.user.id) do %>
          <div><%= image_tag comment.user.get_profile_image(70,70), class: "mt-o rounded-circle"; %></div>
          <div class="text-center"><%= comment.user.name %></div>
        <% end %>
      </div>
      <div class="media-body p-3">
        <div class="row">
          <div class="col-12 pt-3"><%= comment.created_at.strftime('%Y/%m/%d') %></div>
        </div>
        <div class="row">
          <div class="col-8"><%= comment.comment %></div>
          <div class="col-2"><%= link_to '削除', admin_comment_path(comment.id), method: :delete, remote: true, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/comments/destroy.js.erb
$('#comments-count').html("<%= j(render 'admin/comments/count', post: @comment.post) %>")
$('#comments-area').html("<%= j(render 'admin/comments/index', post: @comment.post) %>")

app/views/admin/posts/_favorites-count.html.erb
<% if post.favorites.count != 0 %>
  <p><i class="fas fa-heart" style="color: #ff0000;"></i><%= post.favorites.count %></p>
<% else %>
  <p><i class="far fa-heart" style="color: #000000;"></i>0</p>
<% end %>

app/views/admin/posts/_history.html.erb
<div class="row">
  <div class="d-flex flex-wrap justify-content-evenly col-12">
    <% posts.each do |post| %>
      <div class="card-title">
        　<%= link_to admin_post_path(post.id) do %>
          <%= link_to post.goal, admin_post_path(post.id), class: "text-dark" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/posts/_index.html.erb
<div class="card-list-container mb-5">
  <% posts.each do |post| %>
    <div class="card w-70 mx-auto mb-5 shadow-lg">
      <div class="card-header">
        <span>
          <%= link_to admin_user_path(post.user.id) do %>
            <%= image_tag post.user.get_profile_image(50,50), class: "mt-o rounded-circle"; %>
          <% end %>
        </span>
        <span><%= link_to post.user.name, admin_user_path(post.user.id), class: "text-dark" %></span>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="ml-3">
            <%= render 'admin/posts/favorites-count', post: post %>
          </div>
          <div class="ml-3">
            <%= render 'admin/comments/count', post: post %>
          </div>
          <div class="ml-5">
            <b>
              <% if post.user.released? %>
                <font color="#28a745">公開</font>
              <% elsif post.user.nonreleased? %>
                <font color="#6c757d ">非公開</font>
              <% else %>
                <font color="#dc3545">退会</font>
              <% end %>
            </b>
          </div>
        </div>
        <div class="card-title">
          目標：<%= link_to post.goal, admin_post_path(post.id), class: "text-dark" %>
        </div>
        <div class="card-text">
          具体的な行動：<%= link_to post.action, admin_post_path(post.id), class: "text-dark" %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= paginate posts %>

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-9 mx-auto">
      <div class="card shadow-lg py-3 mb-3">
        <div class="px-3">
          <h2 class="headline col-lg-6 col-md-7 col-sm-12 text-center">投稿一覧</h2>
        </div>
        <div class="col-lg-8 col-md-11 col-sm-12 mx-auto mt-3">
          <%= render 'index', posts: @posts %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-9 mx-auto">
      <div class="card shadow-lg px-3 py-3 mb-3">
        <h2 class="headline col-lg-3 col-md-7 col-sm-12 text-center">投稿詳細</h2>
        <div class="row">
          <div class="col-5 pl-3">
            <%= link_to admin_user_path(@post.user.id) do %>
              <%= image_tag @post.user.get_profile_image(100,100), class: "mt-o rounded-circle"; %>
              <h2><%= @post.user.name %></h2>
              <div><%= render 'admin/posts/favorites-count', post: @post %></div>
            <% end %>
          </div>
          <div class="col-7">
            <dl>
              <dt>投稿日</dt>
              <dd class="post-detail"><%= @post.created_at.strftime('%Y/%m/%d') %></dd>
              <dt>目標</dt>
              <dd class="post-detail"><%= @post.goal %></dd>
              <dt>具体的な目標</dt>
              <dd class="post-detail"><%= @post.action %></dd>
            </dl>
            <%= link_to "投稿を削除", admin_post_path, method: :delete, "data-confirm" => "本当に削除しますか？", class: 'btn btn-danger' %>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-12">
            <h3 class="headline col-lg-4 col-md-7 col-sm-12 text-center">コメント一覧</h3>
            <div id="comments-count">
              <%= render 'admin/comments/count', post: @post %>
            </div>
            <div id="comments-area">
              <%= render 'admin/comments/index', post: @post %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/searches/_form.html.erb
<% if admin_signed_in? %>
  <div class="search_form">
    <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
      <%= f.text_field :content, class: "col-lg-4 col-md-6 col-8",  placeholder: "名前、または目標を入力", value: @content %>
      <%= f.submit '検索', class: "btn btn-sm btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/admin/searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-9 mx-auto">
      <div class="card shadow-lg py-3">
        <% if @users.present? && @posts.present? %>
          <div class="px-3">
            <h3 class="headline col-lg-9 col-md-12 col-sm-12 text-center mb-3">【ユーザーとメニュー名の検索結果】検索ワード："<%= @content %>"</h3>
            <h4>【ユーザー】</h4>
              <%= render 'admin/users/index', users: @users %>
            <hr class="mt-5">
            <h4>【メニュー名】</h4>
          </div>
          <div class="col-lg-8 col-md-8 col-sm-12 mx-auto">
            <%= render 'admin/posts/index', posts: @posts %>
          </div>

        <% elsif @users.present? && @posts.empty? %>
          <div class="px-3">
            <h3 class="headline col-lg-9 col-md-12 col-sm-12 text-center mb-3">【ユーザーの検索結果】検索ワード："<%= @content %>"</h3>
            <h4>【ユーザー】</h4>
            <%= render 'admin/users/index', users: @users %>
          </div>

        <% elsif @users.empty? && @posts.present? %>
          <div class="px-3">
            <h3 class="headline col-lg-9 col-md-12 col-sm-12 text-center mb-3">【メニュー名の検索結果】検索ワード："<%= @content %>"</h3>
            <h4>【メニュー名】</h4>
          </div>
          <div class="col-lg-8 col-md-8 col-sm-12 mx-auto">
            <%= render 'admin/posts/index', posts: @posts %>
          </div>

        <% else %>
          <div class="px-3">
            <h3>"<%= @content %>"に該当はありません。</h3>
          </div>
        <% end %>
      </div>
      <%= link_to '戻る', :back, class: "btn btn-outline-dark mt-3" %>
    </div>
  </div>
</div>

app/views/admin/users/_index.html.erb
<table class="table mb-0">
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td class="text-center">
          <%= link_to admin_user_path(user.id) do %>
            <%= image_tag user.get_profile_image(65,65), class: "users-index-image mt-2 mt-o rounded-circle"; %><br>
          <% end %>
        </td>
        <td>
          <%= link_to admin_user_path(user.id) do %>
            <div class="mt-3"><%= user.name %></div>
          <% end %>
        </td>
        <td class="spview d-none d-sm-block">
          <div class="mt-3">【自己紹介】</div>
          <% if user.name != "guestuser" %>
            <% if user.introduction.present? %>
              <div class="users-index"><%= user.introduction %></div>
            <% else %>
              <div class="users-index">自己紹介文がありません。</div>
            <% end %>
          <% else %>
            <div class="users-index">ゲストユーザーです。</div>
          <% end %>
        </td>
        <td class="text-center">
          <div class="mt-3 text-nowrap">
            <% if user.released? %>
              <%= link_to user.status_i18n, edit_admin_user_path(user.id), class: "btn btn-success" %>
            <% elsif user.nonreleased? %>
              <%= link_to user.status_i18n, edit_admin_user_path(user.id), class: "btn btn-secondary" %>
            <% else %>
              <%= link_to user.status_i18n, edit_admin_user_path(user.id), class: "btn btn-danger" %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<%= paginate users %>

app/views/admin/users/_profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4 mb-3 text-center">
      <%= image_tag user.get_profile_image(120,120), class: "mt-o rounded-circle"; %>
    </div>
    <div class="col-lg-5">
      <div>
        <% if user.released? %>
          <h4><font color="#28a745">公開ユーザーです</font></h4>
        <% elsif user.nonreleased? %>
          <h4><font color="#6c757d">非公開ユーザーです</font></h4>
        <% else %>
          <h4><font color="#dc3545">退会済みユーザーです</font></h4>
        <% end %>
        <strong>名前</strong>:
        <%= user.name %>
      </div>
      <div>投稿件数：<%= user.posts.count %></div>
      <% if user.name != "guestuser" %>
        <div class="row">
          <div class="mx-3">フォロー<%= user.followings.count %>人</div>
          <div>フォロワー<%= user.followers.count %>人</div>
        </div>
        <div class="row">
          <div class="m-3"><%= link_to 'プロフィールを編集', edit_admin_user_path(user.id), class: 'btn btn-sm btn-success', 'data-turbolinks': false %></div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row  pl-3">
    <strong>自己紹介</strong>
  </div>
  <div class="row mb-5">
    <div class="card-text col-12">
      <div class="media border rounded pb-5">
        <% if user.name != "guestuser" %>
          <% if user.introduction.present? %>
            <div><%= user.introduction %></div>
          <% else %>
            <div>自己紹介文がありません</div>
          <% end %>
        <% else %>
          <div>ゲストユーザーです。</div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <h2 class="headline col-lg-4 col-md-7 col-sm-12 text-center">投稿履歴</h2>
    </div>
    <div class="col-12">
      <% if user.posts.present? %>
        <div><%= render 'admin/posts/history', posts: posts %></div>
      <% else %>
        <div>まだ投稿がありません。</div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-9 mx-auto">
      <div class="card shadow-lg px-3 py-3 mb-3">
        <h2 class="headline col-lg-4 col-md-7 col-sm-12 text-center">ユーザー一覧</h2>
        <%= render 'index', users: @users %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-9 mx-auto mb-3">
      <div class="card shadow-lg px-3 py-3">
        <h2 class="headline col-lg-4 col-md-7 col-sm-12 text-center">ユーザー詳細</h2>
        <%= render 'profile', user: @user, posts: @posts %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_admin_sidebar.html.erb
<% if admin_signed_in? %>
<div class="sidebar card text-dark bg-light mb-5 shadow-lg sticky-top">
  <div class="card-header text-center">
    <div class="text-dark">
      <div class="row">
        <div class="col-12">管理者ログイン中</div>
      </div>
    </div>
  </div>
  <div class="card-body">
    <ul class="card-text list-unstyled">
      <li><%= link_to '[投稿]新しい順', admin_root_path(sort: 'latest') %></li>
      <li><%= link_to '[投稿]古い順', admin_root_path(sort: 'old') %></li>
      <li>
        <%= link_to admin_root_path(sort: 'star_count') do %>
          [投稿]<i class="fas fa-star"></i>が多い順
        <% end %>
      </li>
      <li><%= link_to '[投稿]いいね多い順', admin_root_path(sort: 'favorite_count') %></li>
      <li><%= link_to '[投稿]コメント多い順', admin_root_path(sort: 'comment_count') %></li>
    </ul>
  </div>
</div>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= obj.errors.count %>件エラーがあります。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="text-center text-white py-2">
  <div class="copyright"> &copy; 2023 GoalMates Inc. </div>
  <i class="fa-brands fa-twitter px-2"></i>
  <i class="fa-brands fa-line"></i>
  <i class="fa-brands fa-instagram px-2"></i>
  <% if current_page?(root_path) %>
    <div><%= link_to "管理者はこちら", admin_session_path, class: "text-white" %></div>
  <% end %>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark">
    <div class="container">
  　   <% if admin_signed_in? %>
        <%= link_to admin_root_path do %>
          <%= image_tag 'logo.png', width: '70px' %>
        <% end %>
      <% else %>
        <%= link_to root_path do %>
          <%= image_tag 'logo.png', width: '70px' %>
        <% end %>
      <% end %>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Taggle navigaion">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown" style>
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to mypage_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user"></i>マイページ
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_post_path, class: 'nav-link text-light ', 'data-turbolinks': false do %>
                <i class="fas fa-edit"></i>新規投稿
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to posts_path, class: 'nav-link text-light' do %>
                <i class="fas fa-pen-nib"></i>投稿一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i>ユーザー一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to admin_root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-pen-nib"></i>投稿一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  admin_users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i>ユーザー一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to posts_path, class: 'nav-link text-light' do %>
                <i class="fas fa-pen-nib"></i>投稿一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_guest_sign_in_path, class: "nav-link text-light sign_in", method: :post do %>
                <i class="fa-regular fa-user"></i>ゲストログイン
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path , class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i>ログイン
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i>新規登録
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalMates</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f8320138d1.js" crossorigin="anonymous"></script>
  </head>

  <body class="<%= @classname %>">
    <div class="wrapper">
      <div>
        <%= render 'layouts/header' %>
      </div>

      <% if flash[:notice] %>
       <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
       </div>
      <% end %>

      <% if flash[:alert] %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:alert] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>

      <% if admin_signed_in? %>
        <div class="text-center my-4">
          <%= render 'admin/searches/form' %>
        </div>
      <% elsif user_signed_in? %>
        <div class="text-center my-4">
          <%= render 'public/searches/form' %>
        </div>
      <% end %>

      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>